### ISSUE TITLE
Parking garage saving flares

### ISSUE THREAD

**Issue by tylers-dev** [A3Armory/A3A_A3Wasteland_Sock.Altis#19]
Seems upon retrieving a vehicle from parking the flares rearm in a state of 0/1, and won't reload.

**Comment by codexGW** [comment]
I think parking uses the persistence functions from vehicle load so this will affect vehicles after restart to. I tried this and it didn't seem to work. https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/blob/dev/persistence/world/vFunctions.sqf#L376 The only solution I found was to just force the turret to be removed then reinstall it. Not sure if this will work with saved ammo. https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/blob/dev/server/functions/spawnStoreObject.sqf#L247-L253

**Comment by codexGW** [comment]
This fixed this issue in a clunky way.
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/01708324cd4355561c664e1c1c05a8aa07bc0e85

**Comment by codexGW** [comment]
This should fix this and is a bit more refined.
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/4f839fde58bc88c86559a92b35a13023d33ad0d8
