### ISSUE TITLE
MagRepack Black Icons

### ISSUE THREAD

**Issue by Amras86** [A3Armory/A3A_A3Wasteland_Sock.Altis#21]
When opening the MagRepack dialog screen, the magazines listed in the left column all have black icons. Doesn't affect the performance of the addon but its a bit annoying to see the black icons.

To fix it, open:

`addons\outlw_magrepack\Configs\MagRepack_Dialog_Main.hpp`

Go to the line that says:

`class MR_MagListBox: outlw_MR_RscListBox`

Add the following to the config,

`colorPicture[] = {1,1,1,1};`
`colorPictureSelected[] = {1,1,1,1};`
`colorPictureDisabled[] = {1,1,1,1};`

Note: You may also want to add those lines to any other RscListBox in the file just in case.

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/f9c9280a2436e1d9077605871e6ab239c48d0e77

**Comment by codexGW** [comment]
Thanks Amras86 for this fix and AgentRev for this quick implementation. 

Amras86, I added your forum account to the community support group. Send in a support ticket with your uid if you want to be added to the perks.
http://a3armory.com/forum/helpcenter.php
