### ISSUE TITLE
Persistence for Remote Designator and Quadrotor backpacks

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland_Sock.Altis#23]
The Remote Designator and Quadrotor backpacks can not be saved in crates, vehicles, and on players. I don't think this will be to difficult to add to the sock persistence. ExtDB has been doing this for some time.

**Comment by AgentRev** [comment]
I mean, they are just regular backpacks, I don't understand why it wouldn't save with sock, unless micovery added code to explicitly prevent them from being saved

**Comment by codexGW** [comment]
That's what I was hoping for. I thought there was another reason like with the static mortar backpack createvehicle filter bug from after restarts. Where it creates the vehicles from backpacks as local. That was like a 1000 years ago though. It was one of my first post on the A3W forum :smile:

**Comment by tylers-dev** [comment]
Fixed.
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/d65fcfb4cfaa5b2828cf5c69bb446782e1f61b9d
