### ISSUE TITLE
Add Remote Designator to R3F and persistance

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland_Sock.Altis#24]
It would be nice to be able to save (lock) the Remote Designator with R3F and persistence once its been deployed. I believe this is vanilla behavior. It's a bit of a pain to develop because the AI needs to be loaded when the object is spawned back.

**Comment by AgentRev** [comment]
Vanilla doesn't save designators, but that's a good idea. I didn't want to make them too much valuable until I get the chance to bug the shit out of BIS so they add one for indies. Someone asked them a couple months back, but I think the feedback report was marked as "acknowledged" or "reviewed", which roughly translates to "go fuck yourself"

**Comment by codexGW** [comment]
LOL, yeah that is a bummer about indies not having one.

I think I can just add this to a vehicle save and action then just make sure to remove the lock option from R3F (like I did with the mortars) and add its class name to the UAV/UGV vload logic.

**Comment by tylers-dev** [comment]
Remote designator bags can persist in sock now. I don't think we need R3F saving if you can just save the bag.

**Comment by AgentRev** [comment]
He meant saving those deployed throughout the map, so they are restored in working order on each restart, like static weapons.

**Comment by codexGW** [comment]
Saving is working now through weapon assembled like the quadcopters. I didn't even think of that and R3F for movement was already working. It was a lot easier than I thought it would be. :wink: 

https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/80f6d53304e8039c5305c27431aa691ecf1a58f8
