### ISSUE TITLE
Solution for preventing spawn beacon abuse

### ISSUE THREAD

**Issue by tylers-dev** [A3Armory/A3A_A3Wasteland_Sock.Altis#30]
Spawn beacons have a time limit between uses. This can be bypassed with a fresh client compile (jumping back to lobby). Just want to document this to help find the easiest implementation.

**Comment by mooneymoon** [comment]
The beacon can't up and disconnect so maybe track uses via the beacon instead of players?

**Comment by AgentRev** [comment]
I should have a fix up tonight.

**Comment by codexGW** [comment]
This isn't the same issue but I would like to see team beacons only work for online players. We are having problems with people stacking op4 because there is 100's of spawn points to chose from.

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/851fa854f015fb4cabe11495dd7b166a7aba81ec

That was relatively easier than I thought.
