### ISSUE TITLE
Bug in R3F exclude list

### ISSUE THREAD

**Issue by tylers-dev** [A3Armory/A3A_A3Wasteland_Sock.Altis#35]
It appears our R3F exclude towable list isn't working.
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/blob/dev/addons/R3F_ARTY_AND_LOG/R3F_LOG/config.sqf#L144

Player from the forum noted still seeing a tank towing an ammo truck to the water. I also just tested and was still able to tow an ammo truck.
http://a3armory.com/forum/thread-485-page-4.html

I'll dig through the code when I get some time. Maybe it'll teach me some French. ;)

FYI. It doesn't appear to be an issue with vanilla A3W. So something just with Armory code.

**Comment by AgentRev** [comment]
copypaste error: https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/blob/eb78f3fcf4f28fe37dec0eeafe6c67139fa96051/addons/R3F_ARTY_AND_LOG/R3F_LOG/surveiller_conditions_actions_menu.sqf#L197-L198

**Comment by tylers-dev** [comment]
dafuq? are you a fucking robot? how did you find that so fast? That's awesome. Thank you.

**Comment by codexGW** [comment]
Damn curly braces.

Edit: Oops nm, damn objects

**Comment by codexGW** [comment]
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/0052338e9d5c8158911e517783c4799c46746188
