### ISSUE TITLE
Add team switch timer

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland_Sock.Altis#38]
I would like a team switch timer added that will start once you switch or join a team that will prevent players from switching teams again for like 20 minutes. This will help prevent players joining teams to gear up or quickly kill teammates. It would be helpful to have this logged as well because the team switch Battleye filter doesn't seem to work. Oh, have admins bypass the timer as well.

**Comment by AgentRev** [comment]
Player 1 is locked to Blufor. Player 1 wants to go Indie. Player 1 kills friendlies until he is punished away to Indie. Player 1 wins!

**Comment by codexGW** [comment]
Or he could just wait 20 minutes and not lose his gear and be potentially banned, like a normal person. This is a good example of why team kill punishments should be persistent. They aren't even jip persistent now.

**Comment by AgentRev** [comment]
They are and they have _always_ been JIP persistent. Even before I started coding.

**Comment by codexGW** [comment]
Not if they leave before they can be punished... right?

**Comment by AgentRev** [comment]
The UID doesn't get recorded on kill, but I guess that would be a good idea, it only saves the player object as of now, which switches to `objNull` if the TKer leaves. The UID is only acquired and saved when the Punish button is pressed.

**Comment by codexGW** [comment]
Yeah simple stuff like that and a few more admin panel options would be super helpful to avoid having owners and admins dealing with this toxic stuff. They're not as glamours as addons but could really help with owner and admin burnout.

**Comment by AgentRev** [comment]
> a few more admin panel options

like what?

**Comment by codexGW** [comment]
I'll make new issues. I was just doing it :wink:
