### ISSUE TITLE
JumpMF buggy

### ISSUE THREAD

**Issue by tylers-dev** [A3Armory/A3A_A3Wasteland_Sock.Altis#43]
Ever since the 1.58 hotfix about 2 weeks ago that allowed weapon switching while moving. It threw some bugs into the JumpMF addon. Flickering while vaulting, and no vault when holstered and running.

**Comment by mooneymoon** [comment]
When holstered and running you just kind of twitch and can still get over obstacles.

Maybe it is cancelling out animations before they can be carried out?

**Comment by AgentRev** [comment]
Impossible to fix.

**Comment by tylers-dev** [comment]
The vaulting while holstered animation? Is that what's impossible to fix?

**Comment by AgentRev** [comment]
Jumping was not meant to be a part of the game. The only jumping animation available has the unit hold a primary weapon in its hand. When the animation starts playing, if you do not have a primary weapon in your hands, the unit will attempt to switch to an invisible primary weapon, and then revert back to the previous one when landed. This part cannot be fixed. I don't know about holster.

**Comment by tylers-dev** [comment]
Ya that's how it worked before the update. So the update broke that workaround of being able to show the invisible gun vaulting animation?

**Comment by AgentRev** [comment]
No, it's just that the added switching while moving causes a progressive transition to take place instead of instant switching, and that's why it's looking so awkward.

**Comment by AgentRev** [comment]
I managed to get it to jump with the weapon holstered, however on landing the player will do the holster animation without moving legs, if you try to jump again or take out a gun during that time then it fails. The holster animation doesn't want to be cancelled/skipped no matter what I do.

**Comment by codexGW** [comment]
Bummer but definitely not worth to much effort. I'm surprised KK hasn't done more on this.

**Comment by codexGW** [comment]
@A3Wasteland is working on this.
