### ISSUE TITLE
Laser Designator Batteries disappear

### ISSUE THREAD

**Issue by mooneymoon** [A3Armory/A3A_A3Wasteland_Sock.Altis#44]
Players can purchase a laser designator from the store and it will have batteries. Logging out will remove the batteries from the designator.

Here is the fix on extdb2:
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/a6e87b06e80e107b9a57b2d2ae92813cfdafeaca/persistence/client/players/applyPlayerData.sqf#L137

**Comment by codexGW** [comment]
This needs testing but this should do it.
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/05f4a8ee2f74fc1ab045afcf060876dc68bb85fd
