### ISSUE TITLE
Can place a bounty on the headless client

### ISSUE THREAD

**Issue by alostsoldier** [A3Armory/A3A_A3Wasteland_Sock.Altis#45]
You can put a bounty on the headless client. It will take the money however it will not show on the leader boards.

See pictures for clarity:

http://steamcommunity.com/sharedfiles/filedetails/?id=684657317
http://steamcommunity.com/sharedfiles/filedetails/?id=684657327
http://steamcommunity.com/sharedfiles/filedetails/?id=684657346

**Comment by AgentRev** [comment]
Were you logged in as admin?

**Comment by tylers-dev** [comment]
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/blob/dev/client/items/atm/refresh.sqf#L28
_players = _players - entities "HeadlessClient_F";

Adding that line above could fix it. A3W_fnc_isFriendly probably doesn't see headless clients as same side/group, so not friendly would add it as enemy.

**Comment by codexGW** [comment]
> Were you logged in as admin?

He tested this on the main server and has low admin panel but no admin password. Thanks Halifax for this report.

**Comment by AgentRev** [comment]
The `allPlayers` command returns HCs when logged in as admin, but I've heard random occurrences of those being returned even for regular players. Thanks for all the bugs BIS!
