### ISSUE TITLE
Clothing add in - Combat Fatigues Amphibious

### ISSUE THREAD

**Issue by xlucky13z** [A3Armory/A3A_A3Wasteland_Sock.Altis#46]
I was wondering if we could add the in the clothes **Survival Uniform** with the flippers on them. "U_B_Survival_Uniform".  I always look for them and would really appreciate them in game. Would come in handy in many scenarios without having to go full diver.

**Comment by AgentRev** [comment]
I wanted to add it in the vanilla mission, but the problem is that it's Blufor only. Opfor and Indie cannot pick it at all from ground/bodies/crates, so it's not really fair, and problematic if you change side with the uni on.

**Comment by xlucky13z** [comment]
Well who said life is fair? Lol
 I have an idea though. Why not make each team have a small perk like that. Like blufor could be survival uniform. Opfor could have something unique, indie as well. Im not quite sure what though would have do some research.

**Comment by AgentRev** [comment]
And what about if you change side while wearing that uniform? What goes as replacement?

**Comment by xlucky13z** [comment]
Combat fatigues, they are the same thing I believe but without the flippers arent they? 

 I see how that makes things more complicated though.

**Comment by xlucky13z** [comment]
Well maybe it doent. I am on right now and i switched to opfor and now i am an opfor diver. All my gear is same but I have the opfor camo. 

 So just switching to combat fatigues of the other class would work without issue I assume. 

 I was thinking idie doesnt have to have a perk really though. Its lone wolf thats your perk. Or give indie police vests.

 Opfor has the remote designator. 

Boom

**Comment by AgentRev** [comment]
Blufor AND Opfor have remote designators. I will make them factionless once I am done with the extDB migration for A3Armory.

Police vests are kinda shit tho.

**Comment by xlucky13z** [comment]
But so are survival uniforms. Only really good for divers but not many people dive. They are better then police vests though I guess. Ill keep thinking.

**Comment by codexGW** [comment]
@xlucky13z https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/blob/dev/storeConfig.sqf#L435

**Comment by xlucky13z** [comment]
That's Awesome dude Thank you!
