### ISSUE TITLE
disableRemoteSensors

### ISSUE THREAD

**Issue by AgentRev** [A3Armory/A3A_A3Wasteland_Sock.Altis#49]
Hey Giga, could you try adding this line in `A3Wasteland_settings\init.sqf` for all of your servers:

```
true remoteExec ["disableRemoteSensors", 0, true];
```

According to Dwarden and Moricky, this should improve client FPS a bit by disabling useless AI raycast checks, I've never tried it before.

**Comment by codexGW** [comment]
Hell yeah. Anything that might give better performance I'm always willing to try.

**Comment by codexGW** [comment]
Should I add any logging?
`// @file Version: 1.0
//  @file Name: init.sqf
//  @file Author: AgentRev
//  @file Created: 29/06/2013 12:09

// Add custom scripts you wish to be executed on server start here
// config.sqf, admins.sqf, and serverRules.sqf are already loaded automatically

execVM (externalConfigFolder + "\bannedNames.sqf");

true remoteExec ["disableRemoteSensors", 0, true];`

**Comment by AgentRev** [comment]
Nah that looks fine. I don't know how much it will improve it, in my empty test server with all missions enabled I don't see more than a 1-2% increase, but it should normally be a bit more significant in a high-pop server.

**Comment by codexGW** [comment]
Cool, I'll have it on the servers next restart in 2 hours. Anything else you need just ask whenever. You can have full ssh, rdp, or admin password if you wanted. Whatever helps makes it easy for you to test and dev, I'm all for it.
