### ISSUE TITLE
General store "Supplies" tab

### ISSUE THREAD

**Issue by mooneymoon** [A3Armory/A3A_A3Wasteland_Sock.Altis#53]
`12:02:45 Error in expression <if (!isNil "_parentCfg") then
{
switch (configName _parentCfg) do
{
case "CfgVeh>
12:02:45   Error position: <configName _parentCfg) do
{
case "CfgVeh>
12:02:45   Error configname: Type Bool, expected Config entry
12:02:45 File mpmissions\__CUR_MP.Stratis\client\systems\generalStore\populateGenStore.sqf, line 114`

This pops up when one hits the "Supplies" tab on both Stratis and Altis. Chernarus not tested.

**Comment by mooneymoon** [comment]
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/blob/dev/client/systems/generalStore/populateGenStore.sqf#L114

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/fad0633ebd30c294ea956d7c2bd023c67cd81d5e

**Comment by codexGW** [comment]
Thanks Agent and thanks Mooney for the report. I'll put it in at the next
restart.
