### ISSUE TITLE
Help tracking down and error

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland_Sock.Altis#54]
I need help figuring out whats causing this error.

>  5:20:20   Error Undefined variable in expression: getteammarkercolor
>  5:20:20 File mpmissions__CUR_MP.Stratis\territory\client\updateTerritoryMarkers.sqf, line 36
>  5:20:20 Error in expression <etMarkerColorLocal ([_team, false] call getTeamMarkerColor);
> _marker setMarkerBr>
>  5:20:20   Error position: <getTeamMarkerColor);
> _marker setMarkerBr>

This happens when you join the game on independent, I think and during the player load. I think it might have something to do with this.
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/4357b7ac0928e442a46509218738ae0e1bc6c403

**Comment by codexGW** [comment]
It seems to be rare and have to do with what territories are captured. I have seen it once before a couple weeks ago right after the commit I mentioned.

**Comment by AgentRev** [comment]
Yeah there are indeed a couple issues with territory colors, another one for example is when you join Blufor or Opfor, all the territories are dark solid instead of a grid, to indicate that they are yours, but if another one is captured, all the previous ones revert back to the normal grid.

**Comment by codexGW** [comment]
Do you know if this is vanilla behavior? It seems random and I cant really pinpoint what causes it. Both times it happened I joined independent and the last time was right after a restart with no territories captured.

**Comment by AgentRev** [comment]
There are 2 partial errors in the bit you posted, having the full thing would be useful. The file path is always the first line of an error message.

**Comment by codexGW** [comment]
Sorry, had a hard time finding it. Here's the whole bit from my client rpt. I don't think its breaking anything its just more of a ocd thing for me.

> 5:20:18 Group R Alpha 1-1 (0x546a1800) - network ID 2:4851
>  5:20:18  - no main subgroup
>  5:20:20 Scripting function 'bis_fnc_execvm' is not allowed to be remotely executed
>  5:20:20 Error in expression <etMarkerColorLocal ([_team, false] call getTeamMarkerColor);
> _marker setMarkerBr>
>  5:20:20   Error position: <getTeamMarkerColor);
> _marker setMarkerBr>
>  5:20:20   Error Undefined variable in expression: getteammarkercolor
>  5:20:20 File mpmissions__CUR_MP.Stratis\territory\client\updateTerritoryMarkers.sqf, line 36
>  5:20:20 Error in expression <etMarkerColorLocal ([_team, false] call getTeamMarkerColor);
> _marker setMarkerBr>
>  5:20:20   Error position: <getTeamMarkerColor);
> _marker setMarkerBr>
>  5:20:20   Error Undefined variable in expression: getteammarkercolor
>  5:20:20 File mpmissions__CUR_MP.Stratis\territory\client\updateTerritoryMarkers.sqf, line 36
>  5:20:20 Error in expression <etMarkerColorLocal ([_team, false] call getTeamMarkerColor);
> _marker setMarkerBr>
>  5:20:20   Error position: <getTeamMarkerColor);
> _marker setMarkerBr>
>  5:20:20   Error Undefined variable in expression: getteammarkercolor
>  5:20:20 File mpmissions__CUR_MP.Stratis\territory\client\updateTerritoryMarkers.sqf, line 36
>  5:20:20 Error in expression <etMarkerColorLocal ([_team, false] call getTeamMarkerColor);
> _marker setMarkerBr>
>  5:20:20   Error position: <getTeamMarkerColor);
> _marker setMarkerBr>
>  5:20:20   Error Undefined variable in expression: getteammarkercolor
>  5:20:20 File mpmissions__CUR_MP.Stratis\territory\client\updateTerritoryMarkers.sqf, line 36
>  5:20:20 Error in expression <etMarkerColorLocal ([_team, false] call getTeamMarkerColor);
> _marker setMarkerBr>
>  5:20:20   Error position: <getTeamMarkerColor);
> _marker setMarkerBr>
>  5:20:20   Error Undefined variable in expression: getteammarkercolor
>  5:20:20 File mpmissions__CUR_MP.Stratis\territory\client\updateTerritoryMarkers.sqf, line 36
>  5:20:20 Error in expression <etMarkerColorLocal ([_team, false] call getTeamMarkerColor);
> _marker setMarkerBr>
>  5:20:20   Error position: <getTeamMarkerColor);
> _marker setMarkerBr>
>  5:20:20   Error Undefined variable in expression: getteammarkercolor
>  5:20:20 File mpmissions__CUR_MP.Stratis\territory\client\updateTerritoryMarkers.sqf, line 36
>  5:20:20 Error in expression <etMarkerColorLocal ([_team, false] call getTeamMarkerColor);
> _marker setMarkerBr>
>  5:20:20   Error position: <getTeamMarkerColor);
> _marker setMarkerBr>
>  5:20:20   Error Undefined variable in expression: getteammarkercolor
>  5:20:20 File mpmissions__CUR_MP.Stratis\territory\client\updateTerritoryMarkers.sqf, line 36
>  5:20:20 "Loading vehicle misc functions ..."
>  5:20:20 "Loading vehicle misc functions complete"
>  5:20:20 "Loading vector functions ... "
>  5:20:20 "Loading vector functions complete"

**Comment by codexGW** [comment]
Fix
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/899aec06f663d4e7a660110f45f95d443dd8a611
