### ISSUE TITLE
friendlyTags option

### ISSUE THREAD

**Issue by AgentRev** [A3Armory/A3A_A3Wasteland_Sock.Altis#56]
http://forums.a3wasteland.com/index.php?topic=2601.msg15792#msg15792

**Comment by codexGW** [comment]
Thanks for the heads up. I just checked, it's at 0 now.

**Comment by AgentRev** [comment]
If you just edited them now, you have to wait until the server is down, otherwise I think the file will get overwritten.

**Comment by codexGW** [comment]
No they been like that for some time.
