### ISSUE TITLE
Random slam mines appearing

### ISSUE THREAD

**Issue by MrNastyTime** [A3Armory/A3A_A3Wasteland_Sock.Altis#59]
Yesterday I was on a hill east of Pyrgos. No mission nearby or anything. We landed and there where 6 mines near us. Ran over 2 and then as we carried on foot all of a sudden like 8 more just randomly popped up. Not sure if this is a bug related to the random mines spawning now at missions or not.

**Comment by AgentRev** [comment]
All mines are only visible within a 200m radius, if you have a mine detector. All previously-undetected mines will only show up when you get within 15m of them.

**Comment by tylers-dev** [comment]
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/961778a69ba1d18a2e7e92ef8847e7f3cc9e324d

We added SLAM mines to certain AI missions. I think those SLAM mines are left over from a mission. I had forgotten we persist mines. So when the server restarts in the middle of a mission those mines don't get properly cleaned up and then persist into the next restart. I'll look into keeping them from being persisted, or possibly force failing all missions prior to server restart, so they get cleaned up.

**Comment by codexGW** [comment]
Oh that's not good. We should maybe run some clean up scripts to get rid of them. I'll check the database to see how many slam mines we got.

**Comment by codexGW** [comment]
Yeah there's a shit load. Check out the database.The servers objects save every hour as well.

**Comment by mooneymoon** [comment]
That's hilarious. If we left it be those areas would start to be known as DMZs.

**Comment by codexGW** [comment]
I'm trying to get this fixed. Here's what I attempted so far. Need some help getting it to work though.
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/ee1540738d88b60e9448bac9b4be4b4668331f1c

Here's the error I'm getting. Please help with this if you can. I want to push this to the servers soon.

` 7:43:37   Error position: <distance _locations < 85})
};

sh_>
 7:43:37   Error Generic error in expression
 7:43:37 File mpmissions__cur_mp.Altis\persistence\lib\shFunctions.sqf, line 128
 7:43:37 Error in expression < in A3W_saveable_mines_list} && {_class distance _locations < 85})
};

sh_>`
