### ISSUE TITLE
cleanLocationObjects help test

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland_Sock.Altis#64]
I was thinking of removing the uid check in this function so I tested it out. This is what's supposed to clean the mission sites before a mission spawn. Once I realized that it wasn't working, I reverted to vanilla, and still couldn't get it working with non setvariable owneruid items like mines and unlocked R3F items. I only tested this with one money mission spawn but need more info before I make a complete report to A3W. The motivation for this is the CORE group and others on Stratis build walls around the few spawns for money missions. Have you guys experienced anything like I saw but in other missions?

https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/blob/dev/server/missions/factoryMethods/cleanLocationObjects.sqf#L9
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/blob/dev/server/missions/missionProcessor.sqf#L38

**Comment by AgentRev** [comment]
cleanLocationObjects only scans for objects registered via setLocationObjects, which is only called in mission_Outpost

**Comment by codexGW** [comment]
Oh I see, thanks Agent. I will try to add this function to the couple missions that need this. Some people have been playing the game so long they memorized the mission points and set mines and barriers around them.

**Comment by AgentRev** [comment]
You mean outside A3W_poiObjLockDistance?

**Comment by codexGW** [comment]
I didn't get a chance to test the mission lock block at mission markers. Cool though, I just saw [this](https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/blob/dev/addons/R3F_ARTY_AND_LOG/R3F_LOG/objet_deplacable/objectLockStateMachine.sqf#L35) and will add sniper and road block points as well. Should and how will this work at mission land convoys? I would like to add it to the beginning of the land convoys. If it doesn't work yet you think this should be added to vanilla eventually and maybe a clean up for mines?

**Comment by codexGW** [comment]
I did this for now. https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/50419de5a90ca78cc1eab0c1eb90299f3523292e
I will try to add cleanLocationObjects to a few other missions for explosive cleanup.

**Comment by AgentRev** [comment]
That's clever...

Yeah I guess the store bomb radius could be applied to missions too

**Comment by codexGW** [comment]
Oh yeah, I'll try to use that first. I'll probably only use it on the land convoys for now.

**Comment by codexGW** [comment]
Damn cant get the bomb radius to work. This is what I have tried. I think it's this line.
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/c6035697fc8bd2fbd568bea94d6ebda381e5351b#diff-9540fdd057391f9d59afc650c0297c5fR184

**Comment by AgentRev** [comment]
`select [0,8]` means the first 8 characters, none of the strings have 8 characters. use `fn_startsWith` like [this](https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/blob/b82718c2db2077b2524cc0ae6c4dffc06ecb6535/server/functions/network/fn_MPexec.sqf#L110)

**Comment by codexGW** [comment]
Almost there, still having errors with this line though. https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/67d75f0adc109bb688c079d73aff8293b5c5b660#diff-9540fdd057391f9d59afc650c0297c5fR184

> 10:59:45 Error in expression <fn_startsWith);
> if (_isMarker && {_bomb distance _x < _minDist}) exitWith
> {
> dele>
> 10:59:45   Error position: <distance _x < _minDist}) exitWith
> {
> dele>
> 10:59:45   Error distance: Type String, expected Array,Object,Location
> 10:59:45 Error in expression <fn_startsWith);
> if (_isMarker && {_bomb distance _x < _minDist}) exitWith
> {
> dele>
> 10:59:45   Error position: <distance _x < _minDist}) exitWith
> {
> dele>
> 10:59:45   Error Generic error in expression

**Comment by AgentRev** [comment]
`_bomb distance markerPos _x`

**Comment by codexGW** [comment]
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/a653a9e9e7329abc6e18406bb924852a59438508
Thanks man!
