### ISSUE TITLE
Medkits

### ISSUE THREAD

**Issue by xlucky13z** [A3Armory/A3A_A3Wasteland_Sock.Altis#66]
I've noticed trouble with Medkits healing properly. If I have one on me I van no longer heal to 100 with it. Or use it at all besides revive. Also when using on other players takes like 20 tries before it works if it works. Not sure if it was changed or a bug.

**Comment by codexGW** [comment]
Its a long time bug. That's why I added the "Heal self" option when you have a first aid kit (yellow one). That should heal you completely.

**Comment by xlucky13z** [comment]
Yeah yellow ones always work. I just thought the black ones you could use on yourself unlimited times, but they don't work at all besides revive. 
Thanks

**Comment by codexGW** [comment]
I just tried it and it works (Treat Self) full health 100. I think it was that bug or maybe you were a engineer. Everyone else is a medic; snipers, divers, and combat life saver.

**Comment by xlucky13z** [comment]
Yeah was a engineer. Never knew it didn't work with that class.
