### ISSUE TITLE
Artillery load out. 

### ISSUE THREAD

**Issue by xlucky13z** [A3Armory/A3A_A3Wasteland_Sock.Altis#67]
I was thinking how artillery would be cool but it would be to over powered so nobody wants it. 

 I thought of a possible good loading for it though. What if it only came with the cluster mines and a few laser guided shells. 

  Would make it easier to defence mine a base area. Mines are always fun and fair. And a few laser guided shells would be nice for using laser designation more and I am talking like 3 shells or less with maybe 3 of each mines cluster. Sells for about 60 - 80 000. 18000 rearm.

**Comment by AgentRev** [comment]
> cluster mines

![hahaha no](https://m.popkey.co/8bc021/mMLQz.gif)

**Comment by xlucky13z** [comment]
Lol really? Would be cool though. Hilarious with friends if a sudden swarm of mines came down.

**Comment by AgentRev** [comment]
yep and then the admins have to clean the fucking mess because of complaints that there are a thousand mines everywhere

**Comment by xlucky13z** [comment]
Yeah that does sound like it could happen. What about only a couple laser guided shells then.

**Comment by codexGW** [comment]
I did laser guided to the mortars already. Think there's like 8 rounds.

**Comment by xlucky13z** [comment]
Alright fair enough. Close
